### ISSUE TITLE
[BUG] SWAT AI and Taser targetting

### ISSUE THREAD

**Issue by semodo** [eezstreet/SWATEliteForce#423]
SWAT AI doesn't know how to target with a taser. If there is an obstacle between SWAT officer and his target, he will continuously reattempt to shoot his target through the obstacle. SWAT AI should move to a clear line of fire before using taser.

This bug might be related to flashbang blinding though the objects and orders sent thought the objects bugs.

**Comment by CodeAmend** [comment]
This is VERY true. For all versions I have tried.

**Comment by theengineertcr** [comment]
Flashbang blinding through objects as I've stated before is NOT a bug and
is an intentional decision by one of the members on our team -
Jose21crisis. This change was done to allow flashbangs be effective in
small rooms where they would not work many times.

**Comment by holyorangejuice** [comment]
This is still a problem V7 BETA 3. Make it so the officer so up to the target as if he is going to handcuff them, then fire the taser. That should solve issues if possible.

**Comment by sandman332** [comment]
I thought this was fixed as of latest v6 build when the targeting was reworked.  Does this also happen with pepper spray or ordering them to manually deploy pepper-ball gun as well or just taser?

**Comment by holyorangejuice** [comment]
This bug is still happening in v7b3 and only for taser. Pepper spray and
pepper ball have been working well. They tase objects and other swat
officers. They do not clear before firing.

**Comment by holyorangejuice** [comment]
https://www.youtube.com/playlist?list=PLbD-V1bxRmDgk99ezftqgkq2G_cMLHeMZ

This is my current playthrough. I know I have examples in the early videos.
I am at work all weekend. If I can narrow down an example I'llet you know.

**Comment by holyorangejuice** [comment]
https://youtu.be/soj-1lgPVFo

5:35 is taser issue

**Comment by sandman332** [comment]
Interesting, at least the others are still fixed.  I am very short on time these days if I have a chance I will take a look at modifying it.  Now that I remember if you step in front of them while they are trying to do this they will move closer to try and hit the target.  Need to make it so that they start moving closer once already having issues hitting the target.

**Comment by holyorangejuice** [comment]
I understand. Thanks for contacting me. Best of luck.
